version: "3"
services:

  next-prod:
    image: gavink97/dockerizednext:prod
    build:
      context: ${PWD}/next
      dockerfile: Dockerfile.production
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
